name: dbt Job Workflow

# Trigger the workflow on push to main and daily schedule
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'  # every day at 2 AM UTC

jobs:
  dbt_run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dbt + adapter (Snowflake)
      - name: Install dbt and Snowflake adapter
        run: |
          pip install dbt-snowflake==1.10.13

      # Step 4: Configure connection (Secrets)
      - name: Set Snowflake credentials
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: |
          mkdir -p ~/.dbt
          echo "
          snowflake:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: bhcjqdq-shb45366 # AWS account + region
                user: kanikagaikwaddbt
                password: Kritika@1234567890
                role: SYSADMIN
                database: raw
                warehouse: transforming
                schema: jaffle_shop
                threads: 1
                client_session_keep_alive: False
          " > ~/.dbt/profiles.yml

      # Step 5: Run dbt deps (install macros/packages)
      - name: Install dbt dependencies
        run: dbt deps

      # Step 6: Run models
      - name: Run dbt models
        run: dbt run

      # Step 7: Run tests
      - name: Run dbt tests
        run: dbt test

      # Step 8: Check source freshness
      - name: Check source freshness
        run: dbt source freshness
